version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crm-final-project-container
    depends_on:
      - mongodb
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/your_database
      SPRING_DATASOURCE_USERNAME: your_username
      SPRING_DATASOURCE_PASSWORD: your_secure_password
      SPRING_DATA_MONGODB_URI: mongodb://rootuser:rootpass@mongodb:27017/admin
    volumes:
      - ./target:/app
      - ./src:/src
    command: mvn spring-boot:run

  mongodb:
    image: mongo:latest
    container_name: mongodb-dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    volumes:
      - ~/mongodb_data:/data/db
    ports:
      - "27017:27017"

  postgres:
    image: postgres:latest
    container_name: postgres_container-dev
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_secure_password
      POSTGRES_DB: your_database
    volumes:
      - ~/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  mongodb_data:
  postgres_data: