version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    volumes:
      - ~/mongodb_data:/data/db
    ports:
     - "27017:27017"

  postgres:
    image: postgres:latest
    container_name: postgres_container-dev
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_secure_password
      POSTRGRES_DB: your_database
    volumes:
      - ~/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  mongodb_data:
  postgres_data: